# Dockerfile.alertmanager
FROM prom/alertmanager:latest

# Копируем конфигурацию и шаблоны
COPY ./alertmanager/alertmanager.yml /etc/alertmanager/alertmanager.yml
COPY ./templates/ /etc/alertmanager/templates/