global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'feed-rss-server'
    static_configs:
      - targets:
          - 'feed-parser-service_server:8000'

  - job_name: 'feed-parser-service'
    static_configs:
      - targets: ['feed-parser-service_service:8080']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik_traefik:8082']

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100