global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Указываем Alertmanager

rule_files:
  - "alerts.yml"  # Подключаем файл с правилами алертов

scrape_configs:
  - job_name: 'tg_svodd_bot'
    static_configs:
      - targets: ['tg-svodd-bot_tg-svodd-bot :8081']

  - job_name: 'feed-rss-server'
    static_configs:
      - targets:
          - 'feed-parser-service_server:8000'

  - job_name: 'feed-parser-service'
    static_configs:
      - targets: ['feed-parser-service_service:8080']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik_traefik:8082']

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100
    relabel_configs:
      - source_labels: [__address__]
        regex: '10.0.3.27:9100'
        replacement: 'debian11-2cpu-4ram'
        target_label: instance
      - source_labels: [__address__]
        regex: '10.0.3.26:9100'
        replacement: 'husky-zion'
        target_label: instance
      - source_labels: [__address__]
        regex: '10.0.3.31:9100'
        replacement: 'monitoring'
        target_label: instance
      - source_labels: [__address__]
        regex: '10.0.3.30:9100'
        replacement: 'svodd-frontend-1'
        target_label: instance
      - source_labels: [__address__]
        regex: '10.0.3.29:9100'
        replacement: 'svodd-worker-1'
        target_label: instance
        